trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: DockerImageCI
  displayName: 'Docker Image CI'
  steps:
  - checkout: self
      
  - script: |
      cd /../project_app/
    displayName: 'Move to the directory'
    
  - script: |
      docker-compose build
    displayName: 'Build Compose'
    
  - script: |
      docker-compose up -d
    displayName: 'Run Docker Compose'
    
  - task: Docker@2
    displayName: 'Login to Docker Hub'
    inputs:
      command: 'login'
      containerRegistry: 'docker'
      
  - script: |
      docker-compose push
    displayName: 'Push Docker image to Docker Hub'
