name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name:  move to the directory
      run: cd ../test/
      
    - name:  build compose
      run: docker-compose build --build-arg TAG=latest
       
    - name: Run Docker Compose
      run: docker compose up -d
       
    - name: Log into Docker Hub
      uses: docker/login-action@v2
      with:
        username: edmonp173
        password: dckr_pat_j5ap_8CtS34WcS0cQq69PcYjkFI
        
    - name: Push Docker image to Docker Hub
      run: 
        docker compose push

