name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build the Docker image
      run: docker build docke-compose.yaml --file cd ./test/ --tag my-image-name:$(date +%s)
    
    - name: Run Docker Compose
      run: docker-compose up -d
