name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    
    # Add the Docker Compose task here
    - name: Run Docker Compose
      run: |
        docker-compose --file ./path/to/docker-compose.yml up -d
        # Adjust the path based on your actual directory structure
        # Additional commands can be added here if needed
