name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build the Docker image
      run: cd ./test/ |
       docker-compose build 
    
    - name: Run Docker Compose
      run: docker-compose up -d
       
    - name: Log into Docker Hub
      uses: docker/login-action@v2
      with:
        username: edmonp173
        password: dckr_pat_9XEnqfirGLwZycr4mxSG8R-8rZI
        
    - name: Push Docker image to Docker Hub
      run: |
        docker-compose push

